package com.example.springboot.entity;

public class China {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column china.Id
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column china.name
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column china.pid
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    private Integer pid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column china.Id
     *
     * @return the value of china.Id
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column china.Id
     *
     * @param id the value for china.Id
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column china.name
     *
     * @return the value of china.name
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column china.name
     *
     * @param name the value for china.name
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column china.pid
     *
     * @return the value of china.pid
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column china.pid
     *
     * @param pid the value for china.pid
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }
}