package com.example.springboot.entity;

import java.util.Date;

public class CommentHotel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_hotel.id
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_hotel.hotelid
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    private Integer hotelid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_hotel.uid
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_hotel.content
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_hotel.time
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_hotel.id
     *
     * @return the value of comment_hotel.id
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_hotel.id
     *
     * @param id the value for comment_hotel.id
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_hotel.hotelid
     *
     * @return the value of comment_hotel.hotelid
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public Integer getHotelid() {
        return hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_hotel.hotelid
     *
     * @param hotelid the value for comment_hotel.hotelid
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public void setHotelid(Integer hotelid) {
        this.hotelid = hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_hotel.uid
     *
     * @return the value of comment_hotel.uid
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_hotel.uid
     *
     * @param uid the value for comment_hotel.uid
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_hotel.content
     *
     * @return the value of comment_hotel.content
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_hotel.content
     *
     * @param content the value for comment_hotel.content
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_hotel.time
     *
     * @return the value of comment_hotel.time
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_hotel.time
     *
     * @param time the value for comment_hotel.time
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public void setTime(Date time) {
        this.time = time;
    }
}