package com.example.springboot.entity;

public class Foodinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foodinfo.id
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foodinfo.foodname
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    private String foodname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foodinfo.foodprice
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    private Double foodprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foodinfo.description
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foodinfo.foodpic
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    private String foodpic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foodinfo.shopid
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    private Integer shopid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foodinfo.foodstyleid
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    private Integer foodstyleid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foodinfo.id
     *
     * @return the value of foodinfo.id
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foodinfo.id
     *
     * @param id the value for foodinfo.id
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foodinfo.foodname
     *
     * @return the value of foodinfo.foodname
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public String getFoodname() {
        return foodname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foodinfo.foodname
     *
     * @param foodname the value for foodinfo.foodname
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public void setFoodname(String foodname) {
        this.foodname = foodname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foodinfo.foodprice
     *
     * @return the value of foodinfo.foodprice
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public Double getFoodprice() {
        return foodprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foodinfo.foodprice
     *
     * @param foodprice the value for foodinfo.foodprice
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public void setFoodprice(Double foodprice) {
        this.foodprice = foodprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foodinfo.description
     *
     * @return the value of foodinfo.description
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foodinfo.description
     *
     * @param description the value for foodinfo.description
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foodinfo.foodpic
     *
     * @return the value of foodinfo.foodpic
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public String getFoodpic() {
        return foodpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foodinfo.foodpic
     *
     * @param foodpic the value for foodinfo.foodpic
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public void setFoodpic(String foodpic) {
        this.foodpic = foodpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foodinfo.shopid
     *
     * @return the value of foodinfo.shopid
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public Integer getShopid() {
        return shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foodinfo.shopid
     *
     * @param shopid the value for foodinfo.shopid
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public void setShopid(Integer shopid) {
        this.shopid = shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foodinfo.foodstyleid
     *
     * @return the value of foodinfo.foodstyleid
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public Integer getFoodstyleid() {
        return foodstyleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foodinfo.foodstyleid
     *
     * @param foodstyleid the value for foodinfo.foodstyleid
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public void setFoodstyleid(Integer foodstyleid) {
        this.foodstyleid = foodstyleid;
    }
}