package com.example.springboot.entity;

public class HotelRoomtype {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_roomtype.id
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_roomtype.hotelid
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    private Integer hotelid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_roomtype.roomnumber
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    private Integer roomnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_roomtype.roomtypeid
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    private Integer roomtypeid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_roomtype.id
     *
     * @return the value of hotel_roomtype.id
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_roomtype.id
     *
     * @param id the value for hotel_roomtype.id
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_roomtype.hotelid
     *
     * @return the value of hotel_roomtype.hotelid
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public Integer getHotelid() {
        return hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_roomtype.hotelid
     *
     * @param hotelid the value for hotel_roomtype.hotelid
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public void setHotelid(Integer hotelid) {
        this.hotelid = hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_roomtype.roomnumber
     *
     * @return the value of hotel_roomtype.roomnumber
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public Integer getRoomnumber() {
        return roomnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_roomtype.roomnumber
     *
     * @param roomnumber the value for hotel_roomtype.roomnumber
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public void setRoomnumber(Integer roomnumber) {
        this.roomnumber = roomnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_roomtype.roomtypeid
     *
     * @return the value of hotel_roomtype.roomtypeid
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public Integer getRoomtypeid() {
        return roomtypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_roomtype.roomtypeid
     *
     * @param roomtypeid the value for hotel_roomtype.roomtypeid
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public void setRoomtypeid(Integer roomtypeid) {
        this.roomtypeid = roomtypeid;
    }
}