package com.example.springboot.entity;

public class Roomtypeinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomtypeinfo.id
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomtypeinfo.roomtypename
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    private String roomtypename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomtypeinfo.description
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomtypeinfo.id
     *
     * @return the value of roomtypeinfo.id
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomtypeinfo.id
     *
     * @param id the value for roomtypeinfo.id
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomtypeinfo.roomtypename
     *
     * @return the value of roomtypeinfo.roomtypename
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public String getRoomtypename() {
        return roomtypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomtypeinfo.roomtypename
     *
     * @param roomtypename the value for roomtypeinfo.roomtypename
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public void setRoomtypename(String roomtypename) {
        this.roomtypename = roomtypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomtypeinfo.description
     *
     * @return the value of roomtypeinfo.description
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomtypeinfo.description
     *
     * @param description the value for roomtypeinfo.description
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public void setDescription(String description) {
        this.description = description;
    }
}