package com.example.springboot.entity;

public class ShopCollectUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_collect_user.id
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_collect_user.uid
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_collect_user.shopid
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    private Integer shopid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_collect_user.id
     *
     * @return the value of shop_collect_user.id
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_collect_user.id
     *
     * @param id the value for shop_collect_user.id
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_collect_user.uid
     *
     * @return the value of shop_collect_user.uid
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_collect_user.uid
     *
     * @param uid the value for shop_collect_user.uid
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_collect_user.shopid
     *
     * @return the value of shop_collect_user.shopid
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public Integer getShopid() {
        return shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_collect_user.shopid
     *
     * @param shopid the value for shop_collect_user.shopid
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public void setShopid(Integer shopid) {
        this.shopid = shopid;
    }
}