package com.example.springboot.entity;

public class Userinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.id
     *
     * @mbg.generated Sun Jun 09 22:00:19 GMT+08:00 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.uid
     *
     * @mbg.generated Sun Jun 09 22:00:19 GMT+08:00 2019
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.nickname
     *
     * @mbg.generated Sun Jun 09 22:00:19 GMT+08:00 2019
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.icon
     *
     * @mbg.generated Sun Jun 09 22:00:19 GMT+08:00 2019
     */
    private String icon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.id
     *
     * @return the value of userinfo.id
     * @mbg.generated Sun Jun 09 22:00:19 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.id
     *
     * @param id the value for userinfo.id
     * @mbg.generated Sun Jun 09 22:00:19 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.uid
     *
     * @return the value of userinfo.uid
     * @mbg.generated Sun Jun 09 22:00:19 GMT+08:00 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.uid
     *
     * @param uid the value for userinfo.uid
     * @mbg.generated Sun Jun 09 22:00:19 GMT+08:00 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.nickname
     *
     * @return the value of userinfo.nickname
     * @mbg.generated Sun Jun 09 22:00:19 GMT+08:00 2019
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.nickname
     *
     * @param nickname the value for userinfo.nickname
     * @mbg.generated Sun Jun 09 22:00:19 GMT+08:00 2019
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.icon
     *
     * @return the value of userinfo.icon
     * @mbg.generated Sun Jun 09 22:00:19 GMT+08:00 2019
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.icon
     *
     * @param icon the value for userinfo.icon
     * @mbg.generated Sun Jun 09 22:00:19 GMT+08:00 2019
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    @Override
    public String toString() {
        return "Userinfo{" +
                "id=" + id +
                ", uid=" + uid +
                ", nickname='" + nickname + '\'' +
                ", icon='" + icon + '\'' +
                '}';
    }
}