package com.example.springboot.dao;

import com.example.springboot.entity.CommentShop;
import com.example.springboot.entity.CommentShopExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface CommentShopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_shop
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    long countByExample(CommentShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_shop
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int deleteByExample(CommentShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_shop
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_shop
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int insert(CommentShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_shop
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int insertSelective(CommentShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_shop
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    List<CommentShop> selectByExample(CommentShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_shop
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    CommentShop selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_shop
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") CommentShop record, @Param("example") CommentShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_shop
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int updateByExample(@Param("record") CommentShop record, @Param("example") CommentShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_shop
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(CommentShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_shop
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int updateByPrimaryKey(CommentShop record);
}