package com.example.springboot.dao;

import com.example.springboot.entity.HotelCollectUser;
import com.example.springboot.entity.HotelCollectUserExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface HotelCollectUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_collect_user
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    long countByExample(HotelCollectUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_collect_user
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int deleteByExample(HotelCollectUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_collect_user
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_collect_user
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int insert(HotelCollectUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_collect_user
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int insertSelective(HotelCollectUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_collect_user
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    List<HotelCollectUser> selectByExample(HotelCollectUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_collect_user
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    HotelCollectUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_collect_user
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") HotelCollectUser record, @Param("example") HotelCollectUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_collect_user
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int updateByExample(@Param("record") HotelCollectUser record, @Param("example") HotelCollectUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_collect_user
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(HotelCollectUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_collect_user
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int updateByPrimaryKey(HotelCollectUser record);
}