package com.example.springboot.dao;

import com.example.springboot.entity.HotelRoomtype;
import com.example.springboot.entity.HotelRoomtypeExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface HotelRoomtypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_roomtype
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    long countByExample(HotelRoomtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_roomtype
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int deleteByExample(HotelRoomtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_roomtype
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_roomtype
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int insert(HotelRoomtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_roomtype
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int insertSelective(HotelRoomtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_roomtype
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    List<HotelRoomtype> selectByExample(HotelRoomtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_roomtype
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    HotelRoomtype selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_roomtype
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") HotelRoomtype record, @Param("example") HotelRoomtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_roomtype
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int updateByExample(@Param("record") HotelRoomtype record, @Param("example") HotelRoomtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_roomtype
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(HotelRoomtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_roomtype
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int updateByPrimaryKey(HotelRoomtype record);
}