package com.example.springboot.dao;

import com.example.springboot.entity.Shopinfo;
import com.example.springboot.entity.ShopinfoExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface ShopinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    long countByExample(ShopinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int deleteByExample(ShopinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int insert(Shopinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int insertSelective(Shopinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    List<Shopinfo> selectByExample(ShopinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    Shopinfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") Shopinfo record, @Param("example") ShopinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int updateByExample(@Param("record") Shopinfo record, @Param("example") ShopinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(Shopinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int updateByPrimaryKey(Shopinfo record);
}