package com.example.springboot.dao;

import com.example.springboot.entity.CommentHotel;
import com.example.springboot.entity.CommentHotelExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface CommentHotelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_hotel
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    long countByExample(CommentHotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_hotel
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int deleteByExample(CommentHotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_hotel
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_hotel
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int insert(CommentHotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_hotel
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int insertSelective(CommentHotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_hotel
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    List<CommentHotel> selectByExample(CommentHotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_hotel
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    CommentHotel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_hotel
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") CommentHotel record, @Param("example") CommentHotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_hotel
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int updateByExample(@Param("record") CommentHotel record, @Param("example") CommentHotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_hotel
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(CommentHotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_hotel
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int updateByPrimaryKey(CommentHotel record);
}