package com.example.springboot.dao;

import com.example.springboot.entity.Foodinfo;
import com.example.springboot.entity.FoodinfoExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface FoodinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foodinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    long countByExample(FoodinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foodinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int deleteByExample(FoodinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foodinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foodinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int insert(Foodinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foodinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int insertSelective(Foodinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foodinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    List<Foodinfo> selectByExample(FoodinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foodinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    Foodinfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foodinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") Foodinfo record, @Param("example") FoodinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foodinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int updateByExample(@Param("record") Foodinfo record, @Param("example") FoodinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foodinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(Foodinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foodinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int updateByPrimaryKey(Foodinfo record);
}