package com.example.springboot.dao;

import com.example.springboot.entity.Roomtypeinfo;
import com.example.springboot.entity.RoomtypeinfoExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface RoomtypeinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtypeinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    long countByExample(RoomtypeinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtypeinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int deleteByExample(RoomtypeinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtypeinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtypeinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int insert(Roomtypeinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtypeinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int insertSelective(Roomtypeinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtypeinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    List<Roomtypeinfo> selectByExample(RoomtypeinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtypeinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    Roomtypeinfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtypeinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") Roomtypeinfo record, @Param("example") RoomtypeinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtypeinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int updateByExample(@Param("record") Roomtypeinfo record, @Param("example") RoomtypeinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtypeinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(Roomtypeinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomtypeinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int updateByPrimaryKey(Roomtypeinfo record);
}