package com.example.springboot.entity;

public class Foodstyleinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foodstyleinfo.id
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foodstyleinfo.foodstylename
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    private String foodstylename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foodstyleinfo.description
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foodstyleinfo.id
     *
     * @return the value of foodstyleinfo.id
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foodstyleinfo.id
     *
     * @param id the value for foodstyleinfo.id
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foodstyleinfo.foodstylename
     *
     * @return the value of foodstyleinfo.foodstylename
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public String getFoodstylename() {
        return foodstylename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foodstyleinfo.foodstylename
     *
     * @param foodstylename the value for foodstyleinfo.foodstylename
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public void setFoodstylename(String foodstylename) {
        this.foodstylename = foodstylename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foodstyleinfo.description
     *
     * @return the value of foodstyleinfo.description
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foodstyleinfo.description
     *
     * @param description the value for foodstyleinfo.description
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public void setDescription(String description) {
        this.description = description;
    }
}