package com.example.springboot.entity;

public class HotelCollectUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_collect_user.id
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_collect_user.uid
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_collect_user.hotelid
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    private Integer hotelid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_collect_user.id
     *
     * @return the value of hotel_collect_user.id
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_collect_user.id
     *
     * @param id the value for hotel_collect_user.id
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_collect_user.uid
     *
     * @return the value of hotel_collect_user.uid
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_collect_user.uid
     *
     * @param uid the value for hotel_collect_user.uid
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_collect_user.hotelid
     *
     * @return the value of hotel_collect_user.hotelid
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public Integer getHotelid() {
        return hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_collect_user.hotelid
     *
     * @param hotelid the value for hotel_collect_user.hotelid
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public void setHotelid(Integer hotelid) {
        this.hotelid = hotelid;
    }
}