package com.example.springboot.entity;

public class Shopinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopinfo.id
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopinfo.shopname
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    private String shopname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopinfo.shopmark
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    private Double shopmark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopinfo.shopaddress
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    private String shopaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopinfo.chinaid
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    private Integer chinaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopinfo.longitude
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    private Double longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopinfo.latitude
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    private Double latitude;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopinfo.id
     *
     * @return the value of shopinfo.id
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopinfo.id
     *
     * @param id the value for shopinfo.id
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopinfo.shopname
     *
     * @return the value of shopinfo.shopname
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public String getShopname() {
        return shopname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopinfo.shopname
     *
     * @param shopname the value for shopinfo.shopname
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public void setShopname(String shopname) {
        this.shopname = shopname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopinfo.shopmark
     *
     * @return the value of shopinfo.shopmark
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public Double getShopmark() {
        return shopmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopinfo.shopmark
     *
     * @param shopmark the value for shopinfo.shopmark
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public void setShopmark(Double shopmark) {
        this.shopmark = shopmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopinfo.shopaddress
     *
     * @return the value of shopinfo.shopaddress
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public String getShopaddress() {
        return shopaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopinfo.shopaddress
     *
     * @param shopaddress the value for shopinfo.shopaddress
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public void setShopaddress(String shopaddress) {
        this.shopaddress = shopaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopinfo.chinaid
     *
     * @return the value of shopinfo.chinaid
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public Integer getChinaid() {
        return chinaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopinfo.chinaid
     *
     * @param chinaid the value for shopinfo.chinaid
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public void setChinaid(Integer chinaid) {
        this.chinaid = chinaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopinfo.longitude
     *
     * @return the value of shopinfo.longitude
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopinfo.longitude
     *
     * @param longitude the value for shopinfo.longitude
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopinfo.latitude
     *
     * @return the value of shopinfo.latitude
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopinfo.latitude
     *
     * @param latitude the value for shopinfo.latitude
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }
}