package com.example.springboot.entity;

import java.util.Date;

public class CommentShop {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_shop.id
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_shop.shopid
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    private Integer shopid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_shop.uid
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_shop.content
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_shop.time
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_shop.id
     *
     * @return the value of comment_shop.id
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_shop.id
     *
     * @param id the value for comment_shop.id
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_shop.shopid
     *
     * @return the value of comment_shop.shopid
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public Integer getShopid() {
        return shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_shop.shopid
     *
     * @param shopid the value for comment_shop.shopid
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public void setShopid(Integer shopid) {
        this.shopid = shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_shop.uid
     *
     * @return the value of comment_shop.uid
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_shop.uid
     *
     * @param uid the value for comment_shop.uid
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_shop.content
     *
     * @return the value of comment_shop.content
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_shop.content
     *
     * @param content the value for comment_shop.content
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_shop.time
     *
     * @return the value of comment_shop.time
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_shop.time
     *
     * @param time the value for comment_shop.time
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public void setTime(Date time) {
        this.time = time;
    }
}