package com.example.springboot.entity;

public class Hotelinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotelinfo.id
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotelinfo.hotelname
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    private String hotelname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotelinfo.hotelstar
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    private Integer hotelstar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotelinfo.hoteladdress
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    private String hoteladdress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotelinfo.chinaid
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    private Integer chinaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotelinfo.longitude
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    private Double longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotelinfo.latitude
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    private Double latitude;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotelinfo.id
     *
     * @return the value of hotelinfo.id
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotelinfo.id
     *
     * @param id the value for hotelinfo.id
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotelinfo.hotelname
     *
     * @return the value of hotelinfo.hotelname
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public String getHotelname() {
        return hotelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotelinfo.hotelname
     *
     * @param hotelname the value for hotelinfo.hotelname
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public void setHotelname(String hotelname) {
        this.hotelname = hotelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotelinfo.hotelstar
     *
     * @return the value of hotelinfo.hotelstar
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public Integer getHotelstar() {
        return hotelstar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotelinfo.hotelstar
     *
     * @param hotelstar the value for hotelinfo.hotelstar
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public void setHotelstar(Integer hotelstar) {
        this.hotelstar = hotelstar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotelinfo.hoteladdress
     *
     * @return the value of hotelinfo.hoteladdress
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public String getHoteladdress() {
        return hoteladdress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotelinfo.hoteladdress
     *
     * @param hoteladdress the value for hotelinfo.hoteladdress
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public void setHoteladdress(String hoteladdress) {
        this.hoteladdress = hoteladdress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotelinfo.chinaid
     *
     * @return the value of hotelinfo.chinaid
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public Integer getChinaid() {
        return chinaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotelinfo.chinaid
     *
     * @param chinaid the value for hotelinfo.chinaid
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public void setChinaid(Integer chinaid) {
        this.chinaid = chinaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotelinfo.longitude
     *
     * @return the value of hotelinfo.longitude
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotelinfo.longitude
     *
     * @param longitude the value for hotelinfo.longitude
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotelinfo.latitude
     *
     * @return the value of hotelinfo.latitude
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotelinfo.latitude
     *
     * @param latitude the value for hotelinfo.latitude
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }
}