mybatis:
  mapper-locations: classpath:/ch7/mapper/*.xml
  config-location: classpath:/ch7/config/mybatis-config.xml
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/a?characterEncoding=utf8&serverTimezone=UTC&useSSL=false
logging:
  level:
    com.example.repository: debug
