package com.example.springboot.dao;

import com.example.springboot.entity.China;
import com.example.springboot.entity.ChinaExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface ChinaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table china
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    long countByExample(ChinaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table china
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int deleteByExample(ChinaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table china
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table china
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int insert(China record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table china
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int insertSelective(China record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table china
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    List<China> selectByExample(ChinaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table china
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    China selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table china
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") China record, @Param("example") ChinaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table china
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int updateByExample(@Param("record") China record, @Param("example") ChinaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table china
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(China record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table china
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int updateByPrimaryKey(China record);
}