package com.example.springboot.dao;

import com.example.springboot.entity.Foodstyleinfo;
import com.example.springboot.entity.FoodstyleinfoExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface FoodstyleinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foodstyleinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    long countByExample(FoodstyleinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foodstyleinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int deleteByExample(FoodstyleinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foodstyleinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foodstyleinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int insert(Foodstyleinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foodstyleinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int insertSelective(Foodstyleinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foodstyleinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    List<Foodstyleinfo> selectByExample(FoodstyleinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foodstyleinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    Foodstyleinfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foodstyleinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") Foodstyleinfo record, @Param("example") FoodstyleinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foodstyleinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int updateByExample(@Param("record") Foodstyleinfo record, @Param("example") FoodstyleinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foodstyleinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(Foodstyleinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foodstyleinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int updateByPrimaryKey(Foodstyleinfo record);
}