package com.example.springboot.dao;

import com.example.springboot.entity.Hotelinfo;
import com.example.springboot.entity.HotelinfoExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface HotelinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotelinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    long countByExample(HotelinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotelinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int deleteByExample(HotelinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotelinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotelinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int insert(Hotelinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotelinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int insertSelective(Hotelinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotelinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    List<Hotelinfo> selectByExample(HotelinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotelinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    Hotelinfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotelinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") Hotelinfo record, @Param("example") HotelinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotelinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int updateByExample(@Param("record") Hotelinfo record, @Param("example") HotelinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotelinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(Hotelinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotelinfo
     *
     * @mbg.generated Mon Jun 17 18:53:32 GMT+08:00 2019
     */
    int updateByPrimaryKey(Hotelinfo record);
}